name: Crystals Draft
favicon: null
layout_spectrum: 0.26848
typography_spectrum: 0.4682708075270057
title: Crystals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf6d6'
    - '#200a11'
    - '#d27855'
    - '#b5a381'
    - '#a54a32'
  brandStrength: 0.8999760872684419
  lightness: 0.4685388305224478
  saturation: 0.9584805071353912
  rhythmicContrast: 0.2632421087473631
purpose: []
